# Generated by Django 5.2.5 on 2025-08-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
    ]
